# Generated by Django 4.0.3 on 2022-03-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_posting',
            name='title',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_posting',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
