# Generated by Django 4.0.3 on 2022-03-22 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capstoneapi', '0005_alter_applied_posting_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employ', to=settings.AUTH_USER_MODEL),
        ),
    ]
