# Generated by Django 4.0.3 on 2022-03-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapi', '0007_alter_resume_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.ImageField(null=True, upload_to='resumeimages'),
        ),
    ]
