# Generated by Django 4.0.3 on 2022-03-25 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapi', '0008_alter_resume_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_posting',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to='capstoneapi.company'),
        ),
    ]
