from .applicant_serializer import ApplicantSerializer, ApplicantCreateSerializer
from .applied_serializer import AppliedSerializer, AppliedCreateSerializer
from .employer_serializer import EmployerSerializer, EmployerCreateSerializer
from .jobposting_serializer import JobPostingSerializer, JobPostingCreateSerializer
from .resume_serializer import ResumeSerializer, ResumeCreateSerializer
from .skill_serializer import SkillSerializer, SkillCreateSerializer

